---
- name: creating users and file/folders/diectories in it
  hosts: all
  tasks: 
   - name: creating user
     user: 
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
   - name: creating file and directory in user
     file: 
      name: "{{d}}"
      state: "{{e}}"
      owner: "{{f}}"
      group: "{{g}}"
      mode: "{{h}}"
...
