---
- name: start 10 nginx container
  hosts: all
  tasks: 
   - name: start nginx containers
     docker_container: 
      image: nginx
      name: "container{{item}}"
     with_sequence: count=10
...
