---
- name: check if a dir present or not then creating files in it
  hosts: all
  tasks: 
   - name: check if dir present or not
     stat: 
      path: /var1
     register: results
   - name: displaying output of stat module
     debug: 
      var: results
   - name: creating a file init
     file: 
      name: /var1/file1
      state: touch
     when: 
      results.stat.exists == true
...
