---
- name: install tomcat8 using yum&apt module
  hosts: all
  tasks: 
  - block:
    - name: install tomcat8
      apt:
       name: tomcat8
       state: present
    rescue: 
    - name: install tomcat8
      yum:
       name: tomcat8
       state: present
    always: 
    - name: restarting tomcat8
      service:
       name: tomcat8
       state: restarted
...
